config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  resources :users
  resources :assignments do
    resources :submissions
  end  
  resources :locations
  resources :courses
  

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	has_many :submissions
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :location_courses
	has_many :locations, through: :location_courses
	
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :courses, through: :location_courses
	has_many :location_courses
	# has_many :courses

end

app/models/location_course.rb
class LocationCourse < ActiveRecord::Base
	belongs_to :location
	belongs_to :course
	has_many :location_course_users
	has_many :users, through: :location_course_users
end

app/models/location_course_user.rb
class LocationCourseUser < ActiveRecord::Base
	belongs_to :location_course
	belongs_to :user
end

app/models/submission.rb
class Submission < ActiveRecord::Base
	belongs_to :assignment, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # attr_accessible :email, :password, :password_confirmation
         
  has_many :location_course_users
  has_many :location_courses, through: :location_course_users


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(
    :email,
    :password, 
    :password_confirmation, 
    :name, 
    :github_name) }
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
	def index
		@assignments = Assignment.all
	end

	def new
		@assignment = Assignment.new

	end

	def show
		@assignment = Assignment.find params[:id]
	end

	def create
		@assignment = Assignment.create assignment_params
		redirect_to assignments_path
	end
	
	def edit
		@assignment = Assignment.find params[:id]
	end

	def update
		@assignment = Assignment.find params[:id]
		@assignment.update_attributes assignment_params
		redirect_to assignments_path
	end

	def destroy
		@assignment = Assignment.find params[:id]
		@assignment.delete
		redirect_to assignments_path
	end

private
	def assignment_params
		params.require(:assignment).permit(
			:name,
			:requirements
			)
	end	
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses = Course.all
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.create course_params
		redirect_to courses_path
	end	
	
	def edit
		@course = Course.find params[:id]
	end

	def update
		@course = Course.find params[:id]
		@course.update_attributes course_params
		redirect_to courses_path	
	end

	def destroy
		@course = Course.find params[:id]
		@course.delete
		redirect_to courses_path
	end	

private
	def course_params
		params.require(:course).permit(
			:name,
			:description,
			course_ids: [],
			location_ids: []
			)
	end	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	def index
		@locations = Location.all
		# @courses = Course.all
	end

	def new
		@location = Location.new
		@courses = Course.all
	end

	def show
		@location = Location.find params[:id]
		@course = @location.courses
	end

	def create
		@location = Location.create location_params
		@course = @location.courses
		redirect_to locations_path
	end

	def edit
		@location = Location.find params[:id]
		@courses = Course.all
	end

	def update
		@location = Location.find params[:id]
		@location.update_attributes location_params
		@course = @location.courses
		redirect_to locations_path	
	end

	def destroy
		@location = Location.find params[:id]
		@location.destroy
		redirect_to locations_path
	end

private
	def location_params
		params.require(:location).permit(
		:name,
		:address,
		course_ids: [],
		location_ids: []
		)
	end		
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
	def index
		@assignment = Assignment.find params[:assignment_id]
		@submissions = @assignment.submissions
	end

	def show
		@assignment = Assignment.find params[:assignment_id]
		@submission = @assignment.submissions.find params[:id]
	end

	def new
		@assignment = Assignment.find params[:assignment_id]
		@submission = @assignment.submissions.new
	end

	def create
		@assignment = Assignment.find params[:assignment_id]
		@submission = @assignment.submissions.create submission_params
		redirect_to assignment_submissions_path
	end	
	
	def edit
		@assignment = Assignment.find params[:assignment_id]
		@submission = @assignment.submissions.find params[:id]
	end

	def update
		@assignment = Assignment.find params[:assignment_id]
		@submission = @assignment.submissions.find params[:id]
		@submission.update_attributes submission_params
		redirect_to assignment_submissions_path	
	end

	def destroy
		@assignment = Assignment.find params[:assignment_id]
		@submission = @assignment.submissions.find params[:id]
		@submission.delete
		redirect_to assignment_submissions_path
	end	

private
	def submission_params
		params.require(:submission).permit(
			:description,
			:name,
			assignment_ids: [],
			submission_ids: []
			)
	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users= User.all
	end

	def new
		@user = User.new
	end
	
	def create
		@user = User.create user_params
		redirect_to users_path
	end	

	def edit
		@user = User.find params[:id]
	end

	def update
		@user = User.find params[:id]
		@user.update_attributes user_params
		redirect_to users_path
	end

	def destroy
		@user = User.find params[:id]
		@user.delete
		redirect_to users_path
	end
	
private
	def user_params
		params.require(:user).permit(
			:email,
			:password,
			:name,
			:github_name
		)
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
	  def active_link(current_link)
    # puts params.inspect
    # params[:controller] == link_controller ? 'active' : ''
    :active if params[:controller] == current_link
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assignments/_form.html.haml
= form_for @assignment do |f|
	= f.label :name
	= f.text_field :name
	%br
	= f.label :requirements
	= f.text_field :requirements
	%br
	= f.submit

app/views/assignments/edit.html.haml
= render 'form'

app/views/assignments/index.html.haml
%h1 Assignments

- @assignments.each do |f|
	= link_to f.name, assignment_path(f)

	%br
	%br
%br
= link_to "Home", root_path
= link_to "Add Assignment", new_assignment_path

app/views/assignments/new.html.haml
%h1 Add Assignment

= render 'form'

app/views/assignments/show.html.haml
= @assignment.name
%br

= link_to "Edit", edit_assignment_path
%br
= link_to "Delete", assignment_path, method: :delete
%br
= link_to "Assignment Submissions", new_assignment_submission_path(@assignment)

app/views/courses/_form.html.haml
= form_for @course do |f|
	= f.label :name
	= f.text_field :name
	%br
	= f.label :description
	= f.text_area :description
	%br
	= f.submit

app/views/courses/edit.html.haml
= render 'form'

app/views/courses/index.html.haml
%h1 Courses

- @courses.each do |f|
	= f.name
	= f.description
	= link_to "Edit", edit_course_path(f)
	= link_to "Delete", course_path(f), method: :delete
	%br
	%br

%br
= link_to "Home", root_path
= link_to "Add Course", new_course_path

app/views/home/index.html.haml
.container
	.jumbotron.text-center
		%br
		%br
		%br
		%br
		%br
		%h1 Homework Assignment Tracker
		%br
		- if user_signed_in?
			%p
				Welcome #{current_user.name}
		- else
			%p
				= link_to "Login", new_user_session_path, :class => "btn btn-default btn-lg"
				= link_to "Sign up", new_user_registration_path, :class => "btn btn-default btn-lg"

app/views/locations/_form.html.haml
= form_for @location do |f|
	= f.label :name
	= f.text_field :name
	%br
	= f.label :address
	= f.text_field :address
	%br
	- @courses.each do |m|
		= check_box_tag 'location[course_ids][]', m.id, @location.courses.include?(m)
		= m.name
	= f.submit

app/views/locations/edit.html.haml
= render 'form'

app/views/locations/index.html.haml
%h1 Locations

- @locations.each do |f|
	= link_to f.name, location_path(f)
	%br
	%br

%br
= link_to "Home", root_path
= link_to "Add Location", new_location_path

app/views/locations/new.html.haml
%h1 Add Location

= render 'form'

app/views/locations/show.html.haml
= @location.name
= @location.address
- @course.each do |course|
	= course.name
= link_to "Edit", edit_location_path
= link_to "Delete", location_path, method: :delete	

app/views/submissions/_form.html.haml
= form_for [@assignment, @submission] do |f|
	= f.label :description
	= f.text_area :description
	%br
	= f.label :name
	= f.text_field :name
	%br
	= f.submit

app/views/submissions/edit.html.haml
= render 'form'

app/views/submissions/index.html.haml
%h1 Submissions

- @submissions.each do |f|
	= link_to f.name, assignment_submission_path(@assignment, f)
	%br

%br	
= link_to "Home", root_path
= link_to "Submit Assignment", new_assignment_submission_path

app/views/submissions/new.html.haml
%h1 Submit Assignment

= render 'form'

app/views/submissions/show.html.haml
= @submission.name
%br
= @submission.description

app/views/users/_form.html.haml
= form_for @user do |f|
	= f.label :name
	= f.text_field :name
	%br
	= f.label :github_name
	= f.text_field :github_name
	%br
	= f.label :email
	= f.text_field :email
	%br
	= f.label :password
	= f.text_field :password
	%br
	= f.submit

app/views/users/index.html.haml
%h1 Users

- @users.each do |f|
	= f.email
	%br


= link_to "Home", root_path
= link_to "Add New User", new_user_path

app/views/users/new.html.haml
= render 'form'

app/views/users/show.html.haml
@user.email